---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mysql_instance
    image: "geerlingguy/docker-ubuntu2004-ansible:latest"
    published_ports:
      - "3307:3306"
provisioner:
  name: ansible
verifier:
  name: ansible

