---
# Créer le répertoire pour Magento si il n'existe pas
- name: Assurer que le répertoire /var/www/magento existe
  ansible.builtin.file:
    path: "/var/www/magento"
    state: directory
    mode: '0755'

# Télécharger l'archive Magento
- name: Télécharger et installer Magento
  get_url:
    url: "https://github.com/magento/magento2/archive/refs/tags/2.4.3.tar.gz"
    dest: "/tmp/magento.tar.gz"

# Extraire l'archive Magento dans le répertoire `/var/www/magento`
- name: Extraire l'archive Magento
  ansible.builtin.unarchive:
    src: "/tmp/magento.tar.gz"
    dest: "/var/www/magento"
    remote_src: yes

# Définir les permissions appropriées pour le dossier Magento
- name: Définir les permissions du dossier Magento
  ansible.builtin.file:
    path: "/var/www/magento"
    state: directory
    mode: '0755'

# Télécharger le script d'installation de Composer
- name: Télécharger le script d'installation de Composer
  get_url:
    url: "https://getcomposer.org/installer"
    dest: "/tmp/composer-setup.php"

# Installer Composer
- name: Installer Composer
  command:
    cmd: php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Exécuter composer install pour installer les dépendances de Magento
- name: Exécuter composer install
  command:
    cmd: composer install
    chdir: /var/www/magento/magento2-2.4.3/
  become: yes

# Installer Magento via la commande CLI
- name: Installer Magento via la commande CLI
  command:
    cmd: >
      php /var/www/magento/magento2-2.4.3/bin/magento setup:install --base-url=http://magento.davy-data.cloudns.ph --db-host=hostname --db-name=dbname --db-user=davy --db-password=password --backend-frontname=admin --admin-firstname=Prénom --admin-lastname=Nom --admin-email=davy.gerard@gmail.com --admin-user=admin --admin-password=admin123 --language=fr_FR --currency=EUR --timezone=Europe/Paris

