---
- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Remove anonymous MySQL users
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: Créer un utilisateur MySQL pour Magento
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "*.*:ALL"
    state: present

