- name: Installer MySQL
  apt:
    name:
      - mysql-server
    state: present

- name: Créer la base de données pour Magento
  mysql_db:
    name: magento_db
    state: present

- name: Accorder tous les privilèges sur la base de données magento_db
  mysql_user:
    name: magento_user
    password: secret_password
    priv: 'magento_db.*:ALL'
    state: present

