---
- name: Update package cache
  package: 
    update_cache: yes

- name: Install MySQL server
  become: yes
  package:
    name: mysql-server
    state: present

- name: Start MySQL service
  service:
    name: mysql
    state: started
    enabled: yes

